displayName: Java MicroProfile template
description: Cloud Microservice Starter for Java - MicroProfile / Java EE
tags: ["Java", "Maven",]
globalMemoryLimit: 2674Mi
icon: https://www.eclipse.org/che/images/logo-eclipseche.svg
projectType: "liberty"
language: "java"
